In [1]:
import os
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# load ""ManagingABank_AAE625 - Sheet1.csv""
df = pd.read_csv("ManagingABank_AAE625 - Sheet1.csv")
# # convert the "NaN" value in "Team 1 Bid", ""Team 2 Bid", "Team 3 Bid" to 0%
df["Team 1 Bid"] = df["Team 1 Bid"].fillna(0)
df["Team 2 Bid"] = df["Team 2 Bid"].fillna(0)
df["Team 3 Bid"] = df["Team 3 Bid"].fillna(0)
# df["Team 4 Bid"] = df["Team 4 Bid"].fillna(0)
df.head(11)

,Client,Max Willing to Pay Interest Rate,Winning Bid,Winning Team,Team 1 Bid,Team 2 Bid,Team 3 Bid,Amount ($'s),Default,E/A,...,Size,QR,CR,Unnamed: 17,Unnamed: 18,Unnamed: 19,Bonds to Issue,Unnamed: 21,Unnamed: 22,Unnamed: 23
0,Client 1,7%,5.00%,2,0.07,0.07,0.0,"$1,000,000",0,0.62,...,1040.22,2.03,2.51,10.25%,0.00%,NaN,Team 1,Team 2,Team 3,NaN
1,Client 2,5%,5.00%,0,0.00,0.05,0.0,"$1,000,000",0,0.64,...,1015.47,1.56,2.45,0.00%,0.00%,NaN,"($25,000,000.00)","($24,000,000.00)","($25,000,000.00)",NaN
2,Client 3,7%,7.00%,0,0.07,0.07,0.0,"$1,000,000",0,0.64,...,893.21,1.49,2.34,0.00%,0.00%,NaN,NaN,NaN,NaN,NaN
3,Client 4,12%,12.00%,0,0.00,0.00,0.0,"$1,000,000",0,0.16,...,1051.25,2.80,2.41,0.00%,0.00%,NaN,NaN,NaN,NaN,NaN
4,Client 5,7%,7.00%,0,0.07,0.07,0.0,"$1,000,000",0,0.61,...,990.66,2.06,2.41,0.00%,0.00%,NaN,NaN,NaN,NaN,NaN
5,Client 6,11%,11.00%,0,0.00,0.11,0.0,"$1,000,000",0,0.68,...,1004.05,2.32,2.83,0.00%,0.00%,NaN,NaN,NaN,NaN,NaN
6,Client 7,8%,8.00%,0,0.08,0.00,0.0,"$1,000,000",0,0.68,...,967.97,2.55,3.53,0.00%,0.00%,NaN,NaN,NaN,NaN,NaN
7,Client 8,9%,9.00%,0,0.09,0.00,0.0,"$1,000,000",0,0.51,...,1001.13,1.98,2.18,0.00%,0.00%,NaN,NaN,NaN,NaN,NaN
8,Client 9,9%,9.00%,0,0.09,0.00,0.0,"$1,000,000",0,0.51,...,1137.75,2.78,3.17,0.00%,0.00%,NaN,NaN,NaN,NaN,NaN
9,Client 10,11%,11.00%,0,0.00,0.00,0.0,"$1,000,000",0,0.23,...,864.29,1.19,1.74,0.00%,100.00%,NaN,Current $ Loans,NaN,NaN,NaN
10,Client 11,8%,8.00%,0,0.08,0.00,0.0,"$1,000,000",0,0.58,...,1046.25,1.93,2.76,0.00%,0.00%,NaN,Team 1,Team 2,Team 3,NaN

In [6]:
# for each row in the dataframe, if the value in "Team 1 Bid" is not 0,
# check if the value in "Team 1 Bid" is greater than or equal to the value in "Team 2 Bid",
# if so, set the value in "Team 1 Bid" equal to the value in "Team 2 Bid" - 0.0025.
# stop when the value in "Team 1 Bid" is lower than or equal to 0.03

for index, row in df.iterrows():
    if row["Team 1 Bid"] != 0:
        if row["Team 2 Bid"] > row["Team 3 Bid"]:
            if row["Team 1 Bid"] > row["Team 3 Bid"] and row["Team 3 Bid"] > 0.03:
                df.at[index, "Team 1 Bid"] = row["Team 3 Bid"] - 0.0025
            elif row["Team 1 Bid"] == row["Team 2 Bid"]:
                df.at[index, "Team 1 Bid"] = row["Team 2 Bid"] - 0.0025
        elif row["Team 2 Bid"] <= row["Team 3 Bid"]:
            if row["Team 1 Bid"] > row["Team 2 Bid"] and row["Team 2 Bid"] > 0.03:
                df.at[index, "Team 1 Bid"] = row["Team 2 Bid"] - 0.0025
            elif row["Team 1 Bid"] == row["Team 3 Bid"]:
                df.at[index, "Team 1 Bid"] = row["Team 3 Bid"] - 0.0025
        

df.head(11)

,Client,Max Willing to Pay Interest Rate,Winning Bid,Winning Team,Team 1 Bid,Team 2 Bid,Team 3 Bid,Amount ($'s),Default,E/A,...,Size,QR,CR,Unnamed: 17,Unnamed: 18,Unnamed: 19,Bonds to Issue,Unnamed: 21,Unnamed: 22,Unnamed: 23
0,Client 1,7%,5.00%,2,0.0675,0.07,0.0,"$1,000,000",0,0.62,...,1040.22,2.03,2.51,10.25%,0.00%,NaN,Team 1,Team 2,Team 3,NaN
1,Client 2,5%,5.00%,0,0.0000,0.05,0.0,"$1,000,000",0,0.64,...,1015.47,1.56,2.45,0.00%,0.00%,NaN,"($25,000,000.00)","($24,000,000.00)","($25,000,000.00)",NaN
2,Client 3,7%,7.00%,0,0.0675,0.07,0.0,"$1,000,000",0,0.64,...,893.21,1.49,2.34,0.00%,0.00%,NaN,NaN,NaN,NaN,NaN
3,Client 4,12%,12.00%,0,0.0000,0.00,0.0,"$1,000,000",0,0.16,...,1051.25,2.80,2.41,0.00%,0.00%,NaN,NaN,NaN,NaN,NaN
4,Client 5,7%,7.00%,0,0.0675,0.07,0.0,"$1,000,000",0,0.61,...,990.66,2.06,2.41,0.00%,0.00%,NaN,NaN,NaN,NaN,NaN
5,Client 6,11%,11.00%,0,0.0000,0.11,0.0,"$1,000,000",0,0.68,...,1004.05,2.32,2.83,0.00%,0.00%,NaN,NaN,NaN,NaN,NaN
6,Client 7,8%,8.00%,0,0.0800,0.00,0.0,"$1,000,000",0,0.68,...,967.97,2.55,3.53,0.00%,0.00%,NaN,NaN,NaN,NaN,NaN
7,Client 8,9%,9.00%,0,0.0900,0.00,0.0,"$1,000,000",0,0.51,...,1001.13,1.98,2.18,0.00%,0.00%,NaN,NaN,NaN,NaN,NaN
8,Client 9,9%,9.00%,0,0.0900,0.00,0.0,"$1,000,000",0,0.51,...,1137.75,2.78,3.17,0.00%,0.00%,NaN,NaN,NaN,NaN,NaN
9,Client 10,11%,11.00%,0,0.0000,0.00,0.0,"$1,000,000",0,0.23,...,864.29,1.19,1.74,0.00%,100.00%,NaN,Current $ Loans,NaN,NaN,NaN
10,Client 11,8%,8.00%,0,0.0800,0.00,0.0,"$1,000,000",0,0.58,...,1046.25,1.93,2.76,0.00%,0.00%,NaN,Team 1,Team 2,Team 3,NaN

In [7]:
# change the value in "Team 1 Bid" to "NaN" if the value in "Team 1 Bid" is 0
df["Team 1 Bid"] = df["Team 1 Bid"].replace(0, np.nan)

In [8]:
df

,Client,Max Willing to Pay Interest Rate,Winning Bid,Winning Team,Team 1 Bid,Team 2 Bid,Team 3 Bid,Amount ($'s),Default,E/A,...,Size,QR,CR,Unnamed: 17,Unnamed: 18,Unnamed: 19,Bonds to Issue,Unnamed: 21,Unnamed: 22,Unnamed: 23
0,Client 1,7%,5.00%,2,0.0675,0.07,0.00,"$1,000,000",0,0.62,...,1040.22,2.03,2.51,10.25%,0.00%,NaN,Team 1,Team 2,Team 3,NaN
1,Client 2,5%,5.00%,0,NaN,0.05,0.00,"$1,000,000",0,0.64,...,1015.47,1.56,2.45,0.00%,0.00%,NaN,"($25,000,000.00)","($24,000,000.00)","($25,000,000.00)",NaN
2,Client 3,7%,7.00%,0,0.0675,0.07,0.00,"$1,000,000",0,0.64,...,893.21,1.49,2.34,0.00%,0.00%,NaN,NaN,NaN,NaN,NaN
3,Client 4,12%,12.00%,0,NaN,0.00,0.00,"$1,000,000",0,0.16,...,1051.25,2.80,2.41,0.00%,0.00%,NaN,NaN,NaN,NaN,NaN
4,Client 5,7%,7.00%,0,0.0675,0.07,0.00,"$1,000,000",0,0.61,...,990.66,2.06,2.41,0.00%,0.00%,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,Client 496,12%,12.00%,0,NaN,0.00,0.00,"$1,000,000",0,0.31,...,917.03,1.56,1.78,0.00%,0.00%,NaN,NaN,NaN,NaN,NaN
496,Client 497,5%,5.00%,0,NaN,0.05,0.05,"$1,000,000",0,0.72,...,943.02,2.08,3.13,0.00%,0.00%,NaN,NaN,NaN,NaN,NaN
497,Client 498,9%,9.00%,0,0.0675,0.07,0.09,"$1,000,000",0,0.76,...,843.28,2.58,2.44,0.00%,0.00%,NaN,NaN,NaN,NaN,NaN
498,Client 499,9%,9.00%,0,0.0900,0.08,0.00,"$1,000,000",0,0.54,...,927.16,2.26,2.84,0.00%,0.00%,NaN,NaN,NaN,NaN,NaN
499,Client 500,12%,12.00%,0,NaN,0.00,0.00,"$1,000,000",0,0.27,...,985.53,1.53,2.88,0.00%,0.00%,NaN,NaN,NaN,NaN,NaN

In [9]:
# export the dataframe to a csv file named "Final offer.csv"
df.to_csv("Final offer.csv", index=False)